#
#
#
#   --------------------------------------------------------------
#   |                     AdminMode Plugin                       |
#   |   copyright (c) 2022 by Jan Komínek. All rights reserved.  |
#   |      More about a license on my github. Username: H7KZ     |
#   --------------------------------------------------------------
#
#
#

# ****----------------------------------------------****
# **              ADMINMODE PERMISSIONS               **
# ****----------------------------------------------****
# ALL PERMISSIONS
# [adminmode.permissions.all]
# -----
# COMMAND ADMINMODE PERMISSION (use the /'adminmode')
# [adminmode.command.adminmode]
# -----
# COMMAND HELP PERMISSION ('/adminmode help')
# [adminmode.command.help]
# -----
# COMMAND DISABLE PERMISSION (disable the admin mode to yourself '/adminmode disable')
# [adminmode.command.disable]
# -----
# COMMAND ENABLE PERMISSION (enable the admin mode to yourself '/adminmode disable')
# [adminmode.command.enable]
# -----
# COMMAND DISABLE PLAYER PERMISSION (disable the admin mode to a player '/adminmode disable <name>')
# [adminmode.command.disable.player]
# -----
# COMMAND ENABLE PLAYER PERMISSION (enable the admin mode to a player '/adminmode disable <name>')
# [adminmode.command.enable.player]
# -----
# COMMAND CHECK PERMISSION (check if player is in admin mode '/adminmode check <name>')
# [adminmode.command.check]
# -----


# ****----------------------------------------------****
# **             ADMIN MODE ENTER SETTINGS            **
# ****----------------------------------------------****
"enterAdminMode":
  # What to save when you enter the admin mode
  "save":
    # save all player data
    "all": true
    # save inventory
    "inv": true
    # save armor
    "armor": true
    # save experience level
    "exp": true
    # save health
    "health": true
    # save last location
    # by default value is true, meaning you will spawn where you are standing when leaving the admin mode
    "location": true

  # What not to keep when you enter the admin mode
  "erase":
    # erase all player data
    "all": true
    # erase inventory
    "inv": true
    # erase armor
    "armor": true
    # erase experience level
    "exp": true
    # erase health
    "health": true

  # To what change when you enter the admin mode
  "changeTo":
    # change to gamemode
    "gamemode": 1
    # give op
    "op": true


# ****----------------------------------------------****
# **             ADMIN MODE LEAVE SETTINGS            **
# ****----------------------------------------------****
"leaveAdminMode":
  # What to erase when you leave the admin mode
  "erase":
    # erase all player data
    "all": true
    # erase inventory
    "inv": true
    # erase armor
    "armor": true
    # erase experience level
    "exp": true
    # erase health
    "health": true

  # To what change when you leave the admin mode
  "changeTo":
    # change to gamemode
    "gamemode": 0
    # keep op
    "op": false


# ****----------------------------------------------****
# **           ADMIN MODE MESSAGE SETTINGS            **
# ****----------------------------------------------****
"messages":
  "noPermission": "§cAdminMode: You don't have permission to use this command!"
  "notAPlayer": "§cAdminMode: You need to be a player to use this command!"
  "unknownCommand": "§cAdminMode: Unknown command!"
  "noSpecifiedPlayer": "§cAdminMode: You need to specify the name of the player!"
  "playerIsNotOnline": "§cAdminMode: Player is not online!"
  "playerIsNotAdminMode": "§cAdminMode: Player is not in admin mode!"
  "playerIsInAdminMode": "§eAdminMode: Player is currently in admin mode!"
  "reloaded": "§aAdminMode: Plugin reloaded!"