#
#
#
#   --------------------------------------------------------------
#   |                     AdminMode Plugin                       |
#   |   copyright (c) 2022 by Jan Komínek. All rights reserved.  |
#   |      More about a license on my github. Username: H7KZ     |
#   --------------------------------------------------------------
#
#
#

# ****----------------------------------------------****
# **              ADMINMODE PERMISSIONS               **
# ****----------------------------------------------****
# ALL PERMISSIONS
# [adminmode.permissions.all]
# -----
# COMMAND ADMINMODE PERMISSION (use the /'adminmode')
# [adminmode.command.adminmode]
# -----
# COMMAND HELP PERMISSION ('/adminmode help')
# [adminmode.command.help]
# -----
# COMMAND DISABLE PERMISSION (disable the admin mode to yourself '/adminmode disable')
# [adminmode.command.disable]
# -----
# COMMAND ENABLE PERMISSION (enable the admin mode to yourself '/adminmode disable')
# [adminmode.command.enable]
# -----
# COMMAND DISABLE PLAYER PERMISSION (disable the admin mode to a player '/adminmode disable <name>')
# [adminmode.command.disable.player]
# -----
# COMMAND ENABLE PLAYER PERMISSION (enable the admin mode to a player '/adminmode disable <name>')
# [adminmode.command.enable.player]
# -----
# COMMAND CHECK PERMISSION (check if player is in admin mode '/adminmode check <name>')
# [adminmode.command.check]
# -----


# ****----------------------------------------------****
# **             ADMIN MODE ENTER SETTINGS            **
# ****----------------------------------------------****
"enterAdminMode":
  # What to save when you enter the admin mode
  "save":
    # save all player data
    "all": true
    # save inventory
    "inv": true
    # save armor
    "armor": true
    # save experience level
    "exp": true
    # save health
    "health": true
    # save hunger
    "food": true
    # save last location
    # by default value is true, meaning you will spawn where you are standing when leaving the admin mode
    "location": true
    # save last gamemode
    "gamemode": true
    # save op
    "op": true
    # can disable himself from the admin mode, by default value is true
    # (if it is false then the player can't disable himself if he does not have the disabled permission)
    "canDisableHimself": true

  # What not to keep when you enter the admin mode
  "erase":
    # erase all player data
    "all": true
    # erase inventory
    "inv": true
    # erase armor
    "armor": true
    # erase experience level
    "exp": true
    # erase health
    "health": true
    # erase hunger
    "food": true

  # To what change when you enter the admin mode
  "changeTo":
    "player":
      # change to gamemode
      "gamemode": "CREATIVE"
      # give op
      "op": true
    "target":
      # change to gamemode
      "gamemode": "CREATIVE"
      # give op
      "op": false


# ****----------------------------------------------****
# **             ADMIN MODE LEAVE SETTINGS            **
# ****----------------------------------------------****
"leaveAdminMode":
  # What to erase when you leave the admin mode
  "erase":
    # erase all player data
    "all": true
    # erase inventory
    "inv": true
    # erase armor
    "armor": true
    # erase experience level
    "exp": true
    # erase health
    "health": true
    # erase hunger
    "food": true

  # To what change when you leave the admin mode
  "changeTo":
    "player":
      # change to saved gamemode
      "savedGamemode": true
      # change to default gamemode if saved gamemode is false
      "gamemode": "SURVIVAL"
      # change to saved op status
      "savedOp": true
      # load default op if saved op is false
      "op": true
    "target":
      # change to saved gamemode
      "savedGamemode": true
      # change to default gamemode if saved gamemode is false
      "gamemode": "SURVIVAL"
      # change to saved op status
      "savedOp": true
      # load default op if saved op is false
      "op": false


# ****----------------------------------------------****
# **           ADMIN MODE MESSAGE SETTINGS            **
# ****----------------------------------------------****
"messages":
  "sender":
    "noPermission": "AdminMode: You don't have permission to use this command!"
    "notAPlayer": "§cAdminMode: You need to be a player to use this command!"
    "specifyCommand": "AdminMode: You need to specify a command!"
  "player":
    "pluginReloading": "§eAdminMode: Reloading..."
    "pluginReloaded": "§aAdminMode: Plugin reloaded!"

    "noPermission": "§cAdminMode: You don't have permission to use this command!"
    "unknownCommand": "§cAdminMode: Unknown command!"
    "specifyCommand": "§cAdminMode: You need to specify a command!"

    "enabled": "§aAdminMode: You have entered the admin mode!"
    "disabled": "§aAdminMode: You have left the admin mode!"
    "targetEnabled": "§aAdminMode: Player has entered the admin mode!"
    "targetDisabled": "§aAdminMode: Player has left the admin mode!"

    "targetIsNotOnline": "§cAdminMode: Player is not online!"
    "targetIsNotAdminMode": "§cAdminMode: Player is not in admin mode!"
    "targetIsInAdminMode": "§cAdminMode: Player is currently in admin mode!"

    "isInAdminMode": "§cAdminMode: You are currently in admin mode!"
    "isNotInAdminMode": "§cAdminMode: You are not in admin mode!"
  "target":
    "enabled": "§aAdminMode: Some admin made you enter the admin mode!"
    "disabled": "§cAdminMode: Some admin have disabled your admin mode!"