name: AdminMode
version: '${project.version}'
main: me.honzakomi.adminmode.AdminMode
api-version: 1.18
authors: [ HonzaKOMI ]
description: you can go to admin mode and back
website: https://kominek.pages.dev
