name: AdminMode
version: '${project.version}'
main: me.honzakomi.adminmode.AdminMode
api-version: 1.16
authors: [ HonzaKOMI ]
description: Allows you to switch between admin mode and normal mode
website: https://kominekjan.cz
commands:
  AdminMode:
    usage: </command>
    description: /adminmode <command> ('/adminmode help' for more info)