name: AdminMode
version: '${project.version}'
main: me.honzakomi.adminmode.AdminMode
api-version: 1.16
authors: [ HonzaKOMI ]
description: you can go to admin mode and back
website: https://kominekjan.cz
commands:
  AdminMode:
    usage: </command>
    description: makes you go admin mode